# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.26

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/rina/Documents/Github/ekg-ui-library

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/rina/Documents/Github/ekg-ui-library

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/rina/Documents/Github/ekg-ui-library/CMakeFiles /home/rina/Documents/Github/ekg-ui-library//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/rina/Documents/Github/ekg-ui-library/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ekg

# Build rule for target.
ekg: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ekg
.PHONY : ekg

# fast build rule for target.
ekg/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ekg.dir/build.make CMakeFiles/ekg.dir/build
.PHONY : ekg/fast

src/core/runtime.o: src/core/runtime.cpp.o
.PHONY : src/core/runtime.o

# target to build an object file
src/core/runtime.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ekg.dir/build.make CMakeFiles/ekg.dir/src/core/runtime.cpp.o
.PHONY : src/core/runtime.cpp.o

src/core/runtime.i: src/core/runtime.cpp.i
.PHONY : src/core/runtime.i

# target to preprocess a source file
src/core/runtime.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ekg.dir/build.make CMakeFiles/ekg.dir/src/core/runtime.cpp.i
.PHONY : src/core/runtime.cpp.i

src/core/runtime.s: src/core/runtime.cpp.s
.PHONY : src/core/runtime.s

# target to generate assembly for a file
src/core/runtime.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ekg.dir/build.make CMakeFiles/ekg.dir/src/core/runtime.cpp.s
.PHONY : src/core/runtime.cpp.s

src/cpu/event.o: src/cpu/event.cpp.o
.PHONY : src/cpu/event.o

# target to build an object file
src/cpu/event.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ekg.dir/build.make CMakeFiles/ekg.dir/src/cpu/event.cpp.o
.PHONY : src/cpu/event.cpp.o

src/cpu/event.i: src/cpu/event.cpp.i
.PHONY : src/cpu/event.i

# target to preprocess a source file
src/cpu/event.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ekg.dir/build.make CMakeFiles/ekg.dir/src/cpu/event.cpp.i
.PHONY : src/cpu/event.cpp.i

src/cpu/event.s: src/cpu/event.cpp.s
.PHONY : src/cpu/event.s

# target to generate assembly for a file
src/cpu/event.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ekg.dir/build.make CMakeFiles/ekg.dir/src/cpu/event.cpp.s
.PHONY : src/cpu/event.cpp.s

src/draw/draw.o: src/draw/draw.cpp.o
.PHONY : src/draw/draw.o

# target to build an object file
src/draw/draw.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ekg.dir/build.make CMakeFiles/ekg.dir/src/draw/draw.cpp.o
.PHONY : src/draw/draw.cpp.o

src/draw/draw.i: src/draw/draw.cpp.i
.PHONY : src/draw/draw.i

# target to preprocess a source file
src/draw/draw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ekg.dir/build.make CMakeFiles/ekg.dir/src/draw/draw.cpp.i
.PHONY : src/draw/draw.cpp.i

src/draw/draw.s: src/draw/draw.cpp.s
.PHONY : src/draw/draw.s

# target to generate assembly for a file
src/draw/draw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ekg.dir/build.make CMakeFiles/ekg.dir/src/draw/draw.cpp.s
.PHONY : src/draw/draw.cpp.s

src/draw/font.o: src/draw/font.cpp.o
.PHONY : src/draw/font.o

# target to build an object file
src/draw/font.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ekg.dir/build.make CMakeFiles/ekg.dir/src/draw/font.cpp.o
.PHONY : src/draw/font.cpp.o

src/draw/font.i: src/draw/font.cpp.i
.PHONY : src/draw/font.i

# target to preprocess a source file
src/draw/font.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ekg.dir/build.make CMakeFiles/ekg.dir/src/draw/font.cpp.i
.PHONY : src/draw/font.cpp.i

src/draw/font.s: src/draw/font.cpp.s
.PHONY : src/draw/font.s

# target to generate assembly for a file
src/draw/font.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ekg.dir/build.make CMakeFiles/ekg.dir/src/draw/font.cpp.s
.PHONY : src/draw/font.cpp.s

src/ekg.o: src/ekg.cpp.o
.PHONY : src/ekg.o

# target to build an object file
src/ekg.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ekg.dir/build.make CMakeFiles/ekg.dir/src/ekg.cpp.o
.PHONY : src/ekg.cpp.o

src/ekg.i: src/ekg.cpp.i
.PHONY : src/ekg.i

# target to preprocess a source file
src/ekg.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ekg.dir/build.make CMakeFiles/ekg.dir/src/ekg.cpp.i
.PHONY : src/ekg.cpp.i

src/ekg.s: src/ekg.cpp.s
.PHONY : src/ekg.s

# target to generate assembly for a file
src/ekg.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ekg.dir/build.make CMakeFiles/ekg.dir/src/ekg.cpp.s
.PHONY : src/ekg.cpp.s

src/gpu/allocator.o: src/gpu/allocator.cpp.o
.PHONY : src/gpu/allocator.o

# target to build an object file
src/gpu/allocator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ekg.dir/build.make CMakeFiles/ekg.dir/src/gpu/allocator.cpp.o
.PHONY : src/gpu/allocator.cpp.o

src/gpu/allocator.i: src/gpu/allocator.cpp.i
.PHONY : src/gpu/allocator.i

# target to preprocess a source file
src/gpu/allocator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ekg.dir/build.make CMakeFiles/ekg.dir/src/gpu/allocator.cpp.i
.PHONY : src/gpu/allocator.cpp.i

src/gpu/allocator.s: src/gpu/allocator.cpp.s
.PHONY : src/gpu/allocator.s

# target to generate assembly for a file
src/gpu/allocator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ekg.dir/build.make CMakeFiles/ekg.dir/src/gpu/allocator.cpp.s
.PHONY : src/gpu/allocator.cpp.s

src/gpu/data.o: src/gpu/data.cpp.o
.PHONY : src/gpu/data.o

# target to build an object file
src/gpu/data.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ekg.dir/build.make CMakeFiles/ekg.dir/src/gpu/data.cpp.o
.PHONY : src/gpu/data.cpp.o

src/gpu/data.i: src/gpu/data.cpp.i
.PHONY : src/gpu/data.i

# target to preprocess a source file
src/gpu/data.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ekg.dir/build.make CMakeFiles/ekg.dir/src/gpu/data.cpp.i
.PHONY : src/gpu/data.cpp.i

src/gpu/data.s: src/gpu/data.cpp.s
.PHONY : src/gpu/data.s

# target to generate assembly for a file
src/gpu/data.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ekg.dir/build.make CMakeFiles/ekg.dir/src/gpu/data.cpp.s
.PHONY : src/gpu/data.cpp.s

src/gpu/gl.o: src/gpu/gl.cpp.o
.PHONY : src/gpu/gl.o

# target to build an object file
src/gpu/gl.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ekg.dir/build.make CMakeFiles/ekg.dir/src/gpu/gl.cpp.o
.PHONY : src/gpu/gl.cpp.o

src/gpu/gl.i: src/gpu/gl.cpp.i
.PHONY : src/gpu/gl.i

# target to preprocess a source file
src/gpu/gl.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ekg.dir/build.make CMakeFiles/ekg.dir/src/gpu/gl.cpp.i
.PHONY : src/gpu/gl.cpp.i

src/gpu/gl.s: src/gpu/gl.cpp.s
.PHONY : src/gpu/gl.s

# target to generate assembly for a file
src/gpu/gl.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ekg.dir/build.make CMakeFiles/ekg.dir/src/gpu/gl.cpp.s
.PHONY : src/gpu/gl.cpp.s

src/os/info.o: src/os/info.cpp.o
.PHONY : src/os/info.o

# target to build an object file
src/os/info.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ekg.dir/build.make CMakeFiles/ekg.dir/src/os/info.cpp.o
.PHONY : src/os/info.cpp.o

src/os/info.i: src/os/info.cpp.i
.PHONY : src/os/info.i

# target to preprocess a source file
src/os/info.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ekg.dir/build.make CMakeFiles/ekg.dir/src/os/info.cpp.i
.PHONY : src/os/info.cpp.i

src/os/info.s: src/os/info.cpp.s
.PHONY : src/os/info.s

# target to generate assembly for a file
src/os/info.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ekg.dir/build.make CMakeFiles/ekg.dir/src/os/info.cpp.s
.PHONY : src/os/info.cpp.s

src/service/handler.o: src/service/handler.cpp.o
.PHONY : src/service/handler.o

# target to build an object file
src/service/handler.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ekg.dir/build.make CMakeFiles/ekg.dir/src/service/handler.cpp.o
.PHONY : src/service/handler.cpp.o

src/service/handler.i: src/service/handler.cpp.i
.PHONY : src/service/handler.i

# target to preprocess a source file
src/service/handler.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ekg.dir/build.make CMakeFiles/ekg.dir/src/service/handler.cpp.i
.PHONY : src/service/handler.cpp.i

src/service/handler.s: src/service/handler.cpp.s
.PHONY : src/service/handler.s

# target to generate assembly for a file
src/service/handler.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ekg.dir/build.make CMakeFiles/ekg.dir/src/service/handler.cpp.s
.PHONY : src/service/handler.cpp.s

src/service/input.o: src/service/input.cpp.o
.PHONY : src/service/input.o

# target to build an object file
src/service/input.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ekg.dir/build.make CMakeFiles/ekg.dir/src/service/input.cpp.o
.PHONY : src/service/input.cpp.o

src/service/input.i: src/service/input.cpp.i
.PHONY : src/service/input.i

# target to preprocess a source file
src/service/input.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ekg.dir/build.make CMakeFiles/ekg.dir/src/service/input.cpp.i
.PHONY : src/service/input.cpp.i

src/service/input.s: src/service/input.cpp.s
.PHONY : src/service/input.s

# target to generate assembly for a file
src/service/input.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ekg.dir/build.make CMakeFiles/ekg.dir/src/service/input.cpp.s
.PHONY : src/service/input.cpp.s

src/service/layout.o: src/service/layout.cpp.o
.PHONY : src/service/layout.o

# target to build an object file
src/service/layout.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ekg.dir/build.make CMakeFiles/ekg.dir/src/service/layout.cpp.o
.PHONY : src/service/layout.cpp.o

src/service/layout.i: src/service/layout.cpp.i
.PHONY : src/service/layout.i

# target to preprocess a source file
src/service/layout.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ekg.dir/build.make CMakeFiles/ekg.dir/src/service/layout.cpp.i
.PHONY : src/service/layout.cpp.i

src/service/layout.s: src/service/layout.cpp.s
.PHONY : src/service/layout.s

# target to generate assembly for a file
src/service/layout.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ekg.dir/build.make CMakeFiles/ekg.dir/src/service/layout.cpp.s
.PHONY : src/service/layout.cpp.s

src/service/theme.o: src/service/theme.cpp.o
.PHONY : src/service/theme.o

# target to build an object file
src/service/theme.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ekg.dir/build.make CMakeFiles/ekg.dir/src/service/theme.cpp.o
.PHONY : src/service/theme.cpp.o

src/service/theme.i: src/service/theme.cpp.i
.PHONY : src/service/theme.i

# target to preprocess a source file
src/service/theme.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ekg.dir/build.make CMakeFiles/ekg.dir/src/service/theme.cpp.i
.PHONY : src/service/theme.cpp.i

src/service/theme.s: src/service/theme.cpp.s
.PHONY : src/service/theme.s

# target to generate assembly for a file
src/service/theme.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ekg.dir/build.make CMakeFiles/ekg.dir/src/service/theme.cpp.s
.PHONY : src/service/theme.cpp.s

src/ui/abstract/ui_abstract.o: src/ui/abstract/ui_abstract.cpp.o
.PHONY : src/ui/abstract/ui_abstract.o

# target to build an object file
src/ui/abstract/ui_abstract.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ekg.dir/build.make CMakeFiles/ekg.dir/src/ui/abstract/ui_abstract.cpp.o
.PHONY : src/ui/abstract/ui_abstract.cpp.o

src/ui/abstract/ui_abstract.i: src/ui/abstract/ui_abstract.cpp.i
.PHONY : src/ui/abstract/ui_abstract.i

# target to preprocess a source file
src/ui/abstract/ui_abstract.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ekg.dir/build.make CMakeFiles/ekg.dir/src/ui/abstract/ui_abstract.cpp.i
.PHONY : src/ui/abstract/ui_abstract.cpp.i

src/ui/abstract/ui_abstract.s: src/ui/abstract/ui_abstract.cpp.s
.PHONY : src/ui/abstract/ui_abstract.s

# target to generate assembly for a file
src/ui/abstract/ui_abstract.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ekg.dir/build.make CMakeFiles/ekg.dir/src/ui/abstract/ui_abstract.cpp.s
.PHONY : src/ui/abstract/ui_abstract.cpp.s

src/ui/abstract/ui_abstract_widget.o: src/ui/abstract/ui_abstract_widget.cpp.o
.PHONY : src/ui/abstract/ui_abstract_widget.o

# target to build an object file
src/ui/abstract/ui_abstract_widget.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ekg.dir/build.make CMakeFiles/ekg.dir/src/ui/abstract/ui_abstract_widget.cpp.o
.PHONY : src/ui/abstract/ui_abstract_widget.cpp.o

src/ui/abstract/ui_abstract_widget.i: src/ui/abstract/ui_abstract_widget.cpp.i
.PHONY : src/ui/abstract/ui_abstract_widget.i

# target to preprocess a source file
src/ui/abstract/ui_abstract_widget.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ekg.dir/build.make CMakeFiles/ekg.dir/src/ui/abstract/ui_abstract_widget.cpp.i
.PHONY : src/ui/abstract/ui_abstract_widget.cpp.i

src/ui/abstract/ui_abstract_widget.s: src/ui/abstract/ui_abstract_widget.cpp.s
.PHONY : src/ui/abstract/ui_abstract_widget.s

# target to generate assembly for a file
src/ui/abstract/ui_abstract_widget.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ekg.dir/build.make CMakeFiles/ekg.dir/src/ui/abstract/ui_abstract_widget.cpp.s
.PHONY : src/ui/abstract/ui_abstract_widget.cpp.s

src/ui/button/ui_button.o: src/ui/button/ui_button.cpp.o
.PHONY : src/ui/button/ui_button.o

# target to build an object file
src/ui/button/ui_button.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ekg.dir/build.make CMakeFiles/ekg.dir/src/ui/button/ui_button.cpp.o
.PHONY : src/ui/button/ui_button.cpp.o

src/ui/button/ui_button.i: src/ui/button/ui_button.cpp.i
.PHONY : src/ui/button/ui_button.i

# target to preprocess a source file
src/ui/button/ui_button.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ekg.dir/build.make CMakeFiles/ekg.dir/src/ui/button/ui_button.cpp.i
.PHONY : src/ui/button/ui_button.cpp.i

src/ui/button/ui_button.s: src/ui/button/ui_button.cpp.s
.PHONY : src/ui/button/ui_button.s

# target to generate assembly for a file
src/ui/button/ui_button.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ekg.dir/build.make CMakeFiles/ekg.dir/src/ui/button/ui_button.cpp.s
.PHONY : src/ui/button/ui_button.cpp.s

src/ui/button/ui_button_widget.o: src/ui/button/ui_button_widget.cpp.o
.PHONY : src/ui/button/ui_button_widget.o

# target to build an object file
src/ui/button/ui_button_widget.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ekg.dir/build.make CMakeFiles/ekg.dir/src/ui/button/ui_button_widget.cpp.o
.PHONY : src/ui/button/ui_button_widget.cpp.o

src/ui/button/ui_button_widget.i: src/ui/button/ui_button_widget.cpp.i
.PHONY : src/ui/button/ui_button_widget.i

# target to preprocess a source file
src/ui/button/ui_button_widget.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ekg.dir/build.make CMakeFiles/ekg.dir/src/ui/button/ui_button_widget.cpp.i
.PHONY : src/ui/button/ui_button_widget.cpp.i

src/ui/button/ui_button_widget.s: src/ui/button/ui_button_widget.cpp.s
.PHONY : src/ui/button/ui_button_widget.s

# target to generate assembly for a file
src/ui/button/ui_button_widget.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ekg.dir/build.make CMakeFiles/ekg.dir/src/ui/button/ui_button_widget.cpp.s
.PHONY : src/ui/button/ui_button_widget.cpp.s

src/ui/checkbox/ui_checkbox.o: src/ui/checkbox/ui_checkbox.cpp.o
.PHONY : src/ui/checkbox/ui_checkbox.o

# target to build an object file
src/ui/checkbox/ui_checkbox.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ekg.dir/build.make CMakeFiles/ekg.dir/src/ui/checkbox/ui_checkbox.cpp.o
.PHONY : src/ui/checkbox/ui_checkbox.cpp.o

src/ui/checkbox/ui_checkbox.i: src/ui/checkbox/ui_checkbox.cpp.i
.PHONY : src/ui/checkbox/ui_checkbox.i

# target to preprocess a source file
src/ui/checkbox/ui_checkbox.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ekg.dir/build.make CMakeFiles/ekg.dir/src/ui/checkbox/ui_checkbox.cpp.i
.PHONY : src/ui/checkbox/ui_checkbox.cpp.i

src/ui/checkbox/ui_checkbox.s: src/ui/checkbox/ui_checkbox.cpp.s
.PHONY : src/ui/checkbox/ui_checkbox.s

# target to generate assembly for a file
src/ui/checkbox/ui_checkbox.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ekg.dir/build.make CMakeFiles/ekg.dir/src/ui/checkbox/ui_checkbox.cpp.s
.PHONY : src/ui/checkbox/ui_checkbox.cpp.s

src/ui/checkbox/ui_checkbox_widget.o: src/ui/checkbox/ui_checkbox_widget.cpp.o
.PHONY : src/ui/checkbox/ui_checkbox_widget.o

# target to build an object file
src/ui/checkbox/ui_checkbox_widget.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ekg.dir/build.make CMakeFiles/ekg.dir/src/ui/checkbox/ui_checkbox_widget.cpp.o
.PHONY : src/ui/checkbox/ui_checkbox_widget.cpp.o

src/ui/checkbox/ui_checkbox_widget.i: src/ui/checkbox/ui_checkbox_widget.cpp.i
.PHONY : src/ui/checkbox/ui_checkbox_widget.i

# target to preprocess a source file
src/ui/checkbox/ui_checkbox_widget.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ekg.dir/build.make CMakeFiles/ekg.dir/src/ui/checkbox/ui_checkbox_widget.cpp.i
.PHONY : src/ui/checkbox/ui_checkbox_widget.cpp.i

src/ui/checkbox/ui_checkbox_widget.s: src/ui/checkbox/ui_checkbox_widget.cpp.s
.PHONY : src/ui/checkbox/ui_checkbox_widget.s

# target to generate assembly for a file
src/ui/checkbox/ui_checkbox_widget.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ekg.dir/build.make CMakeFiles/ekg.dir/src/ui/checkbox/ui_checkbox_widget.cpp.s
.PHONY : src/ui/checkbox/ui_checkbox_widget.cpp.s

src/ui/frame/ui_frame.o: src/ui/frame/ui_frame.cpp.o
.PHONY : src/ui/frame/ui_frame.o

# target to build an object file
src/ui/frame/ui_frame.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ekg.dir/build.make CMakeFiles/ekg.dir/src/ui/frame/ui_frame.cpp.o
.PHONY : src/ui/frame/ui_frame.cpp.o

src/ui/frame/ui_frame.i: src/ui/frame/ui_frame.cpp.i
.PHONY : src/ui/frame/ui_frame.i

# target to preprocess a source file
src/ui/frame/ui_frame.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ekg.dir/build.make CMakeFiles/ekg.dir/src/ui/frame/ui_frame.cpp.i
.PHONY : src/ui/frame/ui_frame.cpp.i

src/ui/frame/ui_frame.s: src/ui/frame/ui_frame.cpp.s
.PHONY : src/ui/frame/ui_frame.s

# target to generate assembly for a file
src/ui/frame/ui_frame.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ekg.dir/build.make CMakeFiles/ekg.dir/src/ui/frame/ui_frame.cpp.s
.PHONY : src/ui/frame/ui_frame.cpp.s

src/ui/frame/ui_frame_widget.o: src/ui/frame/ui_frame_widget.cpp.o
.PHONY : src/ui/frame/ui_frame_widget.o

# target to build an object file
src/ui/frame/ui_frame_widget.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ekg.dir/build.make CMakeFiles/ekg.dir/src/ui/frame/ui_frame_widget.cpp.o
.PHONY : src/ui/frame/ui_frame_widget.cpp.o

src/ui/frame/ui_frame_widget.i: src/ui/frame/ui_frame_widget.cpp.i
.PHONY : src/ui/frame/ui_frame_widget.i

# target to preprocess a source file
src/ui/frame/ui_frame_widget.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ekg.dir/build.make CMakeFiles/ekg.dir/src/ui/frame/ui_frame_widget.cpp.i
.PHONY : src/ui/frame/ui_frame_widget.cpp.i

src/ui/frame/ui_frame_widget.s: src/ui/frame/ui_frame_widget.cpp.s
.PHONY : src/ui/frame/ui_frame_widget.s

# target to generate assembly for a file
src/ui/frame/ui_frame_widget.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ekg.dir/build.make CMakeFiles/ekg.dir/src/ui/frame/ui_frame_widget.cpp.s
.PHONY : src/ui/frame/ui_frame_widget.cpp.s

src/ui/label/ui_label.o: src/ui/label/ui_label.cpp.o
.PHONY : src/ui/label/ui_label.o

# target to build an object file
src/ui/label/ui_label.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ekg.dir/build.make CMakeFiles/ekg.dir/src/ui/label/ui_label.cpp.o
.PHONY : src/ui/label/ui_label.cpp.o

src/ui/label/ui_label.i: src/ui/label/ui_label.cpp.i
.PHONY : src/ui/label/ui_label.i

# target to preprocess a source file
src/ui/label/ui_label.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ekg.dir/build.make CMakeFiles/ekg.dir/src/ui/label/ui_label.cpp.i
.PHONY : src/ui/label/ui_label.cpp.i

src/ui/label/ui_label.s: src/ui/label/ui_label.cpp.s
.PHONY : src/ui/label/ui_label.s

# target to generate assembly for a file
src/ui/label/ui_label.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ekg.dir/build.make CMakeFiles/ekg.dir/src/ui/label/ui_label.cpp.s
.PHONY : src/ui/label/ui_label.cpp.s

src/ui/label/ui_label_widget.o: src/ui/label/ui_label_widget.cpp.o
.PHONY : src/ui/label/ui_label_widget.o

# target to build an object file
src/ui/label/ui_label_widget.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ekg.dir/build.make CMakeFiles/ekg.dir/src/ui/label/ui_label_widget.cpp.o
.PHONY : src/ui/label/ui_label_widget.cpp.o

src/ui/label/ui_label_widget.i: src/ui/label/ui_label_widget.cpp.i
.PHONY : src/ui/label/ui_label_widget.i

# target to preprocess a source file
src/ui/label/ui_label_widget.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ekg.dir/build.make CMakeFiles/ekg.dir/src/ui/label/ui_label_widget.cpp.i
.PHONY : src/ui/label/ui_label_widget.cpp.i

src/ui/label/ui_label_widget.s: src/ui/label/ui_label_widget.cpp.s
.PHONY : src/ui/label/ui_label_widget.s

# target to generate assembly for a file
src/ui/label/ui_label_widget.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ekg.dir/build.make CMakeFiles/ekg.dir/src/ui/label/ui_label_widget.cpp.s
.PHONY : src/ui/label/ui_label_widget.cpp.s

src/ui/popup/ui_popup.o: src/ui/popup/ui_popup.cpp.o
.PHONY : src/ui/popup/ui_popup.o

# target to build an object file
src/ui/popup/ui_popup.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ekg.dir/build.make CMakeFiles/ekg.dir/src/ui/popup/ui_popup.cpp.o
.PHONY : src/ui/popup/ui_popup.cpp.o

src/ui/popup/ui_popup.i: src/ui/popup/ui_popup.cpp.i
.PHONY : src/ui/popup/ui_popup.i

# target to preprocess a source file
src/ui/popup/ui_popup.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ekg.dir/build.make CMakeFiles/ekg.dir/src/ui/popup/ui_popup.cpp.i
.PHONY : src/ui/popup/ui_popup.cpp.i

src/ui/popup/ui_popup.s: src/ui/popup/ui_popup.cpp.s
.PHONY : src/ui/popup/ui_popup.s

# target to generate assembly for a file
src/ui/popup/ui_popup.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ekg.dir/build.make CMakeFiles/ekg.dir/src/ui/popup/ui_popup.cpp.s
.PHONY : src/ui/popup/ui_popup.cpp.s

src/ui/popup/ui_popup_widget.o: src/ui/popup/ui_popup_widget.cpp.o
.PHONY : src/ui/popup/ui_popup_widget.o

# target to build an object file
src/ui/popup/ui_popup_widget.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ekg.dir/build.make CMakeFiles/ekg.dir/src/ui/popup/ui_popup_widget.cpp.o
.PHONY : src/ui/popup/ui_popup_widget.cpp.o

src/ui/popup/ui_popup_widget.i: src/ui/popup/ui_popup_widget.cpp.i
.PHONY : src/ui/popup/ui_popup_widget.i

# target to preprocess a source file
src/ui/popup/ui_popup_widget.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ekg.dir/build.make CMakeFiles/ekg.dir/src/ui/popup/ui_popup_widget.cpp.i
.PHONY : src/ui/popup/ui_popup_widget.cpp.i

src/ui/popup/ui_popup_widget.s: src/ui/popup/ui_popup_widget.cpp.s
.PHONY : src/ui/popup/ui_popup_widget.s

# target to generate assembly for a file
src/ui/popup/ui_popup_widget.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ekg.dir/build.make CMakeFiles/ekg.dir/src/ui/popup/ui_popup_widget.cpp.s
.PHONY : src/ui/popup/ui_popup_widget.cpp.s

src/ui/scroll/ui_scroll_embedded_widget.o: src/ui/scroll/ui_scroll_embedded_widget.cpp.o
.PHONY : src/ui/scroll/ui_scroll_embedded_widget.o

# target to build an object file
src/ui/scroll/ui_scroll_embedded_widget.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ekg.dir/build.make CMakeFiles/ekg.dir/src/ui/scroll/ui_scroll_embedded_widget.cpp.o
.PHONY : src/ui/scroll/ui_scroll_embedded_widget.cpp.o

src/ui/scroll/ui_scroll_embedded_widget.i: src/ui/scroll/ui_scroll_embedded_widget.cpp.i
.PHONY : src/ui/scroll/ui_scroll_embedded_widget.i

# target to preprocess a source file
src/ui/scroll/ui_scroll_embedded_widget.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ekg.dir/build.make CMakeFiles/ekg.dir/src/ui/scroll/ui_scroll_embedded_widget.cpp.i
.PHONY : src/ui/scroll/ui_scroll_embedded_widget.cpp.i

src/ui/scroll/ui_scroll_embedded_widget.s: src/ui/scroll/ui_scroll_embedded_widget.cpp.s
.PHONY : src/ui/scroll/ui_scroll_embedded_widget.s

# target to generate assembly for a file
src/ui/scroll/ui_scroll_embedded_widget.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ekg.dir/build.make CMakeFiles/ekg.dir/src/ui/scroll/ui_scroll_embedded_widget.cpp.s
.PHONY : src/ui/scroll/ui_scroll_embedded_widget.cpp.s

src/ui/scroll/ui_scroll_widget.o: src/ui/scroll/ui_scroll_widget.cpp.o
.PHONY : src/ui/scroll/ui_scroll_widget.o

# target to build an object file
src/ui/scroll/ui_scroll_widget.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ekg.dir/build.make CMakeFiles/ekg.dir/src/ui/scroll/ui_scroll_widget.cpp.o
.PHONY : src/ui/scroll/ui_scroll_widget.cpp.o

src/ui/scroll/ui_scroll_widget.i: src/ui/scroll/ui_scroll_widget.cpp.i
.PHONY : src/ui/scroll/ui_scroll_widget.i

# target to preprocess a source file
src/ui/scroll/ui_scroll_widget.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ekg.dir/build.make CMakeFiles/ekg.dir/src/ui/scroll/ui_scroll_widget.cpp.i
.PHONY : src/ui/scroll/ui_scroll_widget.cpp.i

src/ui/scroll/ui_scroll_widget.s: src/ui/scroll/ui_scroll_widget.cpp.s
.PHONY : src/ui/scroll/ui_scroll_widget.s

# target to generate assembly for a file
src/ui/scroll/ui_scroll_widget.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ekg.dir/build.make CMakeFiles/ekg.dir/src/ui/scroll/ui_scroll_widget.cpp.s
.PHONY : src/ui/scroll/ui_scroll_widget.cpp.s

src/ui/slider/ui_slider.o: src/ui/slider/ui_slider.cpp.o
.PHONY : src/ui/slider/ui_slider.o

# target to build an object file
src/ui/slider/ui_slider.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ekg.dir/build.make CMakeFiles/ekg.dir/src/ui/slider/ui_slider.cpp.o
.PHONY : src/ui/slider/ui_slider.cpp.o

src/ui/slider/ui_slider.i: src/ui/slider/ui_slider.cpp.i
.PHONY : src/ui/slider/ui_slider.i

# target to preprocess a source file
src/ui/slider/ui_slider.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ekg.dir/build.make CMakeFiles/ekg.dir/src/ui/slider/ui_slider.cpp.i
.PHONY : src/ui/slider/ui_slider.cpp.i

src/ui/slider/ui_slider.s: src/ui/slider/ui_slider.cpp.s
.PHONY : src/ui/slider/ui_slider.s

# target to generate assembly for a file
src/ui/slider/ui_slider.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ekg.dir/build.make CMakeFiles/ekg.dir/src/ui/slider/ui_slider.cpp.s
.PHONY : src/ui/slider/ui_slider.cpp.s

src/ui/slider/ui_slider_widget.o: src/ui/slider/ui_slider_widget.cpp.o
.PHONY : src/ui/slider/ui_slider_widget.o

# target to build an object file
src/ui/slider/ui_slider_widget.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ekg.dir/build.make CMakeFiles/ekg.dir/src/ui/slider/ui_slider_widget.cpp.o
.PHONY : src/ui/slider/ui_slider_widget.cpp.o

src/ui/slider/ui_slider_widget.i: src/ui/slider/ui_slider_widget.cpp.i
.PHONY : src/ui/slider/ui_slider_widget.i

# target to preprocess a source file
src/ui/slider/ui_slider_widget.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ekg.dir/build.make CMakeFiles/ekg.dir/src/ui/slider/ui_slider_widget.cpp.i
.PHONY : src/ui/slider/ui_slider_widget.cpp.i

src/ui/slider/ui_slider_widget.s: src/ui/slider/ui_slider_widget.cpp.s
.PHONY : src/ui/slider/ui_slider_widget.s

# target to generate assembly for a file
src/ui/slider/ui_slider_widget.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ekg.dir/build.make CMakeFiles/ekg.dir/src/ui/slider/ui_slider_widget.cpp.s
.PHONY : src/ui/slider/ui_slider_widget.cpp.s

src/ui/textbox/ui_textbox.o: src/ui/textbox/ui_textbox.cpp.o
.PHONY : src/ui/textbox/ui_textbox.o

# target to build an object file
src/ui/textbox/ui_textbox.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ekg.dir/build.make CMakeFiles/ekg.dir/src/ui/textbox/ui_textbox.cpp.o
.PHONY : src/ui/textbox/ui_textbox.cpp.o

src/ui/textbox/ui_textbox.i: src/ui/textbox/ui_textbox.cpp.i
.PHONY : src/ui/textbox/ui_textbox.i

# target to preprocess a source file
src/ui/textbox/ui_textbox.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ekg.dir/build.make CMakeFiles/ekg.dir/src/ui/textbox/ui_textbox.cpp.i
.PHONY : src/ui/textbox/ui_textbox.cpp.i

src/ui/textbox/ui_textbox.s: src/ui/textbox/ui_textbox.cpp.s
.PHONY : src/ui/textbox/ui_textbox.s

# target to generate assembly for a file
src/ui/textbox/ui_textbox.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ekg.dir/build.make CMakeFiles/ekg.dir/src/ui/textbox/ui_textbox.cpp.s
.PHONY : src/ui/textbox/ui_textbox.cpp.s

src/ui/textbox/ui_textbox_widget.o: src/ui/textbox/ui_textbox_widget.cpp.o
.PHONY : src/ui/textbox/ui_textbox_widget.o

# target to build an object file
src/ui/textbox/ui_textbox_widget.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ekg.dir/build.make CMakeFiles/ekg.dir/src/ui/textbox/ui_textbox_widget.cpp.o
.PHONY : src/ui/textbox/ui_textbox_widget.cpp.o

src/ui/textbox/ui_textbox_widget.i: src/ui/textbox/ui_textbox_widget.cpp.i
.PHONY : src/ui/textbox/ui_textbox_widget.i

# target to preprocess a source file
src/ui/textbox/ui_textbox_widget.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ekg.dir/build.make CMakeFiles/ekg.dir/src/ui/textbox/ui_textbox_widget.cpp.i
.PHONY : src/ui/textbox/ui_textbox_widget.cpp.i

src/ui/textbox/ui_textbox_widget.s: src/ui/textbox/ui_textbox_widget.cpp.s
.PHONY : src/ui/textbox/ui_textbox_widget.s

# target to generate assembly for a file
src/ui/textbox/ui_textbox_widget.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ekg.dir/build.make CMakeFiles/ekg.dir/src/ui/textbox/ui_textbox_widget.cpp.s
.PHONY : src/ui/textbox/ui_textbox_widget.cpp.s

src/util/env.o: src/util/env.cpp.o
.PHONY : src/util/env.o

# target to build an object file
src/util/env.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ekg.dir/build.make CMakeFiles/ekg.dir/src/util/env.cpp.o
.PHONY : src/util/env.cpp.o

src/util/env.i: src/util/env.cpp.i
.PHONY : src/util/env.i

# target to preprocess a source file
src/util/env.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ekg.dir/build.make CMakeFiles/ekg.dir/src/util/env.cpp.i
.PHONY : src/util/env.cpp.i

src/util/env.s: src/util/env.cpp.s
.PHONY : src/util/env.s

# target to generate assembly for a file
src/util/env.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ekg.dir/build.make CMakeFiles/ekg.dir/src/util/env.cpp.s
.PHONY : src/util/env.cpp.s

src/util/geometry.o: src/util/geometry.cpp.o
.PHONY : src/util/geometry.o

# target to build an object file
src/util/geometry.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ekg.dir/build.make CMakeFiles/ekg.dir/src/util/geometry.cpp.o
.PHONY : src/util/geometry.cpp.o

src/util/geometry.i: src/util/geometry.cpp.i
.PHONY : src/util/geometry.i

# target to preprocess a source file
src/util/geometry.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ekg.dir/build.make CMakeFiles/ekg.dir/src/util/geometry.cpp.i
.PHONY : src/util/geometry.cpp.i

src/util/geometry.s: src/util/geometry.cpp.s
.PHONY : src/util/geometry.s

# target to generate assembly for a file
src/util/geometry.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ekg.dir/build.make CMakeFiles/ekg.dir/src/util/geometry.cpp.s
.PHONY : src/util/geometry.cpp.s

src/util/util_event.o: src/util/util_event.cpp.o
.PHONY : src/util/util_event.o

# target to build an object file
src/util/util_event.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ekg.dir/build.make CMakeFiles/ekg.dir/src/util/util_event.cpp.o
.PHONY : src/util/util_event.cpp.o

src/util/util_event.i: src/util/util_event.cpp.i
.PHONY : src/util/util_event.i

# target to preprocess a source file
src/util/util_event.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ekg.dir/build.make CMakeFiles/ekg.dir/src/util/util_event.cpp.i
.PHONY : src/util/util_event.cpp.i

src/util/util_event.s: src/util/util_event.cpp.s
.PHONY : src/util/util_event.s

# target to generate assembly for a file
src/util/util_event.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ekg.dir/build.make CMakeFiles/ekg.dir/src/util/util_event.cpp.s
.PHONY : src/util/util_event.cpp.s

src/util/util_ui.o: src/util/util_ui.cpp.o
.PHONY : src/util/util_ui.o

# target to build an object file
src/util/util_ui.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ekg.dir/build.make CMakeFiles/ekg.dir/src/util/util_ui.cpp.o
.PHONY : src/util/util_ui.cpp.o

src/util/util_ui.i: src/util/util_ui.cpp.i
.PHONY : src/util/util_ui.i

# target to preprocess a source file
src/util/util_ui.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ekg.dir/build.make CMakeFiles/ekg.dir/src/util/util_ui.cpp.i
.PHONY : src/util/util_ui.cpp.i

src/util/util_ui.s: src/util/util_ui.cpp.s
.PHONY : src/util/util_ui.s

# target to generate assembly for a file
src/util/util_ui.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ekg.dir/build.make CMakeFiles/ekg.dir/src/util/util_ui.cpp.s
.PHONY : src/util/util_ui.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... ekg"
	@echo "... src/core/runtime.o"
	@echo "... src/core/runtime.i"
	@echo "... src/core/runtime.s"
	@echo "... src/cpu/event.o"
	@echo "... src/cpu/event.i"
	@echo "... src/cpu/event.s"
	@echo "... src/draw/draw.o"
	@echo "... src/draw/draw.i"
	@echo "... src/draw/draw.s"
	@echo "... src/draw/font.o"
	@echo "... src/draw/font.i"
	@echo "... src/draw/font.s"
	@echo "... src/ekg.o"
	@echo "... src/ekg.i"
	@echo "... src/ekg.s"
	@echo "... src/gpu/allocator.o"
	@echo "... src/gpu/allocator.i"
	@echo "... src/gpu/allocator.s"
	@echo "... src/gpu/data.o"
	@echo "... src/gpu/data.i"
	@echo "... src/gpu/data.s"
	@echo "... src/gpu/gl.o"
	@echo "... src/gpu/gl.i"
	@echo "... src/gpu/gl.s"
	@echo "... src/os/info.o"
	@echo "... src/os/info.i"
	@echo "... src/os/info.s"
	@echo "... src/service/handler.o"
	@echo "... src/service/handler.i"
	@echo "... src/service/handler.s"
	@echo "... src/service/input.o"
	@echo "... src/service/input.i"
	@echo "... src/service/input.s"
	@echo "... src/service/layout.o"
	@echo "... src/service/layout.i"
	@echo "... src/service/layout.s"
	@echo "... src/service/theme.o"
	@echo "... src/service/theme.i"
	@echo "... src/service/theme.s"
	@echo "... src/ui/abstract/ui_abstract.o"
	@echo "... src/ui/abstract/ui_abstract.i"
	@echo "... src/ui/abstract/ui_abstract.s"
	@echo "... src/ui/abstract/ui_abstract_widget.o"
	@echo "... src/ui/abstract/ui_abstract_widget.i"
	@echo "... src/ui/abstract/ui_abstract_widget.s"
	@echo "... src/ui/button/ui_button.o"
	@echo "... src/ui/button/ui_button.i"
	@echo "... src/ui/button/ui_button.s"
	@echo "... src/ui/button/ui_button_widget.o"
	@echo "... src/ui/button/ui_button_widget.i"
	@echo "... src/ui/button/ui_button_widget.s"
	@echo "... src/ui/checkbox/ui_checkbox.o"
	@echo "... src/ui/checkbox/ui_checkbox.i"
	@echo "... src/ui/checkbox/ui_checkbox.s"
	@echo "... src/ui/checkbox/ui_checkbox_widget.o"
	@echo "... src/ui/checkbox/ui_checkbox_widget.i"
	@echo "... src/ui/checkbox/ui_checkbox_widget.s"
	@echo "... src/ui/frame/ui_frame.o"
	@echo "... src/ui/frame/ui_frame.i"
	@echo "... src/ui/frame/ui_frame.s"
	@echo "... src/ui/frame/ui_frame_widget.o"
	@echo "... src/ui/frame/ui_frame_widget.i"
	@echo "... src/ui/frame/ui_frame_widget.s"
	@echo "... src/ui/label/ui_label.o"
	@echo "... src/ui/label/ui_label.i"
	@echo "... src/ui/label/ui_label.s"
	@echo "... src/ui/label/ui_label_widget.o"
	@echo "... src/ui/label/ui_label_widget.i"
	@echo "... src/ui/label/ui_label_widget.s"
	@echo "... src/ui/popup/ui_popup.o"
	@echo "... src/ui/popup/ui_popup.i"
	@echo "... src/ui/popup/ui_popup.s"
	@echo "... src/ui/popup/ui_popup_widget.o"
	@echo "... src/ui/popup/ui_popup_widget.i"
	@echo "... src/ui/popup/ui_popup_widget.s"
	@echo "... src/ui/scroll/ui_scroll_embedded_widget.o"
	@echo "... src/ui/scroll/ui_scroll_embedded_widget.i"
	@echo "... src/ui/scroll/ui_scroll_embedded_widget.s"
	@echo "... src/ui/scroll/ui_scroll_widget.o"
	@echo "... src/ui/scroll/ui_scroll_widget.i"
	@echo "... src/ui/scroll/ui_scroll_widget.s"
	@echo "... src/ui/slider/ui_slider.o"
	@echo "... src/ui/slider/ui_slider.i"
	@echo "... src/ui/slider/ui_slider.s"
	@echo "... src/ui/slider/ui_slider_widget.o"
	@echo "... src/ui/slider/ui_slider_widget.i"
	@echo "... src/ui/slider/ui_slider_widget.s"
	@echo "... src/ui/textbox/ui_textbox.o"
	@echo "... src/ui/textbox/ui_textbox.i"
	@echo "... src/ui/textbox/ui_textbox.s"
	@echo "... src/ui/textbox/ui_textbox_widget.o"
	@echo "... src/ui/textbox/ui_textbox_widget.i"
	@echo "... src/ui/textbox/ui_textbox_widget.s"
	@echo "... src/util/env.o"
	@echo "... src/util/env.i"
	@echo "... src/util/env.s"
	@echo "... src/util/geometry.o"
	@echo "... src/util/geometry.i"
	@echo "... src/util/geometry.s"
	@echo "... src/util/util_event.o"
	@echo "... src/util/util_event.i"
	@echo "... src/util/util_event.s"
	@echo "... src/util/util_ui.o"
	@echo "... src/util/util_ui.i"
	@echo "... src/util/util_ui.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

